지도 경로 표시 기능 구현 및 홈페이지 코스 데이터 연동했습니다.
codestates-seb/seb41_main_026 pull request #37
Opened 2023-01-12 03:29 UTC by yolodion

1. 지도 경로 표시 기능 구현
2. 홈페이지 코스 데이터 연동

2023-01-12 05:01 UTC, marco0332 requested changes
컴포넌트 상에서 사용하는 데이터가 모든 상황에서 존재한다라는 가정하에 작성된 코드로 보입니다.
[optional chaining](https://ko.javascript.info/optional-chaining)을 활용해서 데이터가 없더라도 컴포넌트가 에러를 발생시키지 않도록 수정이 필요합니다.

2023-01-12 07:31 UTC, yolodion commented on client/src/components/RegionSection/RegionSection.jsx
> +        {locationData !== null &&
네!! 감사합니다

2023-01-12 07:32 UTC, yolodion commented on client/src/components/RegionSection/RegionSection.jsx
> +      .then(res => setLocationData(res));
바로 넣으면 될것 같습니다 ㅎ_ㅎ 감사합니다

2023-01-12 07:32 UTC, yolodion commented on client/src/components/RegionSection/RegionSection.jsx
> +  console.log(locationData);
네!

2023-01-12 07:33 UTC, yolodion commented on client/src/pages/ContentPage/ContentPage.jsx
> +                  <Polyline
네! 알겠습니다

2023-01-12 07:39 UTC, yolodion commented on client/src/pages/ContentPage/ContentPage.jsx
> +                  <Polyline
const [pathCoordinates, setPathCoordinates] = useState([
    [
      { lat: 37.5512141, lng: 126.9882024 },
      { lat: 37.739235, lng: 126.99025 },
    ],
    [
      { lat: 37.739235, lng: 126.99025 },
      { lat: 37.052235, lng: 126.243683 },
    ],
    [
      { lat: 37.052235, lng: 126.243683 },
      { lat: 37.712776, lng: 126.005974 },
    ],
  ]);

Polyline의 path props에는 위도, 경도의 2세트 배열을 넘겨줘야해서 id 값을 어떻게 짜야할지 모르겠습니다.
백엔드에서 만들 데이터를 제가 임시로 짜서 넣다보니 고민이 필요할것 같습니다.

2023-01-12 07:43 UTC, marco0332 commented on client/src/pages/ContentPage/ContentPage.jsx
> +                  <Polyline
@yolodion 
임시로 `coord_${index}`의 형식으로 key값을 사용하고, api가 완료되면 데이터 unique key로 변경하는 방향이 좋아보입니다.

2023-01-12 07:58 UTC, yolodion commented on client/src/pages/ContentPage/ContentPage.jsx
> +                  <Polyline
네 그렇게 하겠습니다!

2023-01-12 07:58 UTC, yolodion commented on client/src/pages/ContentPage/ContentPage.jsx
> +                  <Polyline
감사합니다

2023-01-13 00:11 UTC, yolodion commented on client/src/pages/ContentPage/ContentPage.jsx
>    const [focus1, setFocus1] = useState(false);
각 버튼이 고유하게 클릭되도록 상태를 만들어놔서 변경이 어렵네요 ㅠㅠ

2023-01-13 02:35 UTC, merged